apiRules:
- exclude:
    uidRegex: ^ErronkaApi\.(Logak|Mapeoak|Middlewareak|Modeloak|NHibernate|Repositorioak|Testak)
    type: Type
- include:
    uidRegex: ^ErronkaApi\.(DTOak|Kontrollerrak)
    type: Type
